export interface Solicitation{
    id?: number
    request_number: string
    bank_proposal: string
    document_name: string
    sub_document?: string
    state_id: string
    state: string
    city: string
    uf: string
    property_registration_office?: string
    civil_register_office?: string
    register_number?: string
    applicant_name_one?: string
    applicant_name_two?: string
    applicant_cpf_on?: string
    applicant_cpf_two?: string
    birth_date?: string
    wedding_date?: string
    death_date?: string
    municipal_registration_property?: string
    request_status: string
    request_date: string
    request_hour: string
    requestor_name: string
    requestor_register: string
    bank_op: string
    forecast_date: string
    forecast_weeK_day: string
    operator_name?: string
    operator_register?: string
    operator_op?: string
    image?: string
    image_name?: string
    image_type?: string
    image_size?: number
    start_process_date?: string
    start_process_hour?: string
    finish_process_date?: string
    finish_process_hour?: string
}